name: CLI Installation Tests

env:
  ACTIONS_STEP_DEBUG: true

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-native-installers:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, windows-latest, macos-latest]
        include:
          - os: windows-latest
            installer_path: 'https://github.com/NeuraLegion/bright-cli/releases/latest/download/bright-cli.msi'
            verify_cmd: 'bright-cli --version'
            installer_type: 'msi'
          - os: windows-latest
            installer_path: 'https://github.com/NeuraLegion/bright-cli/releases/latest/download/bright-cli-win-x64.exe'
            verify_cmd: 'bright-cli --version'
            installer_type: 'exe'
          - os: ubuntu-latest
            installer_path: 'https://github.com/NeuraLegion/bright-cli/releases/latest/download/bright-cli-linux-x64'
            verify_cmd: 'bright-cli --version'
          - os: macos-latest
            installer_path: 'https://github.com/NeuraLegion/bright-cli/releases/latest/download/bright-cli-macos-x64'
            verify_cmd: 'bright-cli --version'
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Bright CLI (Windows MSI)
      if: matrix.os == 'windows-latest' && matrix.installer_type == 'msi'
      run: |
        # Download and install
        Invoke-WebRequest -Uri ${{ matrix.installer_path }} -OutFile bright-cli.msi
        Start-Process msiexec.exe -Wait -ArgumentList '/I bright-cli.msi /quiet'
    
    - name: Install Bright CLI (Windows EXE)
      if: matrix.os == 'windows-latest' && matrix.installer_type == 'exe'
      run: |
        # Download and install
        Invoke-WebRequest -Uri ${{ matrix.installer_path }} -OutFile bright-cli.exe
        Start-Process bright-cli.exe -Wait -ArgumentList '/quiet'
    
    - name: Install Bright CLI (Linux/MacOS)
      if: matrix.os != 'windows-latest'
      run: |
        curl --compressed ${{ matrix.installer_path }} -o bright-cli
        chmod +x bright-cli
        sudo ./bright-cli

    - name: Verify Installation
      run: |
        echo "Running verification command: ${{ matrix.verify_cmd }}"
        echo "Command output:"
        ${{ matrix.verify_cmd }}

  test-docker:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Pull and test Docker image
      run: |
        docker pull brightsec/cli:latest
        docker run brightsec/cli:latest --version

  test-npm:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install via npm
      run: |
        npm i -g @brightsec/cli
    
    - name: Verify npm installation
      run: bright-cli --version